{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'hv-switching-board' %}
{% set LIB_NAME = 'HVSwitchingBoard' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
  noarch: python
  script:
    # Copy Arduino library to Conda include directory and generate Arduino `library.properties` file
    - python file_handler.py {{ SRC_DIR }} {{ PREFIX }} {{ PKG_NAME }} {{ MODULE_NAME }} {{ LIB_NAME }}
    # Install source directory as Python package.
    - python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python >=3.6
    - numpy
    - base-node
    - pytables
    - platformio
    - base-node-rpc
    - path-helpers
    - nanopb-helpers
    - dropbot-headers
    - platformio-helpers
    - serial-device
    - pip

  run:
    - python >=3.6
    - base-node
    - pytables
    - platformio
    - base-node-rpc
    - nanopb-helpers
    - dropbot-headers
    - platformio-helpers
    - serial-device
    - pip

test:
  imports:
    - {{ MODULE_NAME }}

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: MIT
  summary: Arduino-based high-voltage switching board firmware and Python API.

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
#  git_url: ../
  path: ..